import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  DxDrawerModule, 
  DxToolbarModule,
  DxBoxModule, DxPopoverModule,
  DxProgressBarModule,
  DxFileUploaderModule, 
  DxPopupModule,
  DxDataGridModule,
  DxFormModule,
  DxButtonModule,
  DxTextBoxModule,
  DxSelectBoxModule,
  DxTextAreaModule,
  DxNumberBoxModule,
  DxAutocompleteModule,
  DxButtonGroupModule,
  DxSwitchModule,
  DxListModule,
  DxDateBoxModule,
  DxTagBoxModule,
  DxDropDownBoxModule,
  DxTabsModule,
  DxTabPanelModule,
  DxCheckBoxModule,
  DxValidatorModule,
  DxAccordionModule,
  DxContextMenuModule,
  DxRadioGroupModule,
  DxLookupModule,
  DxTooltipModule,
  DxSliderModule,
  DxGalleryModule
} from 'devextreme-angular';


@NgModule({
  declarations: [],
  imports: [DxDrawerModule, 
    DxToolbarModule,
    DxBoxModule, DxPopoverModule,
    DxFileUploaderModule,
    DxPopupModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxTextBoxModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxNumberBoxModule,
    DxAutocompleteModule,
    DxSwitchModule,
    DxListModule,
    DxDateBoxModule,
    DxTagBoxModule,
    DxDropDownBoxModule,
    DxTabsModule,
    DxTabPanelModule,
    DxCheckBoxModule,
    DxValidatorModule,
    DxAccordionModule,
    DxProgressBarModule,
    DxRadioGroupModule,
    DxContextMenuModule,
    DxButtonGroupModule,
    DxTooltipModule,
    DxSliderModule,
    DxGalleryModule
  ],
  exports: [   
    DxBoxModule, DxPopoverModule,
    DxProgressBarModule,
    DxFileUploaderModule,
    DxPopupModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxTextBoxModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxNumberBoxModule,
    DxAutocompleteModule,
    DxSwitchModule,
    DxListModule,
    DxDateBoxModule,
    DxTagBoxModule,
    DxDropDownBoxModule,
    DxTabsModule,
    DxTabPanelModule,
    DxCheckBoxModule,
    DxValidatorModule,
    DxAccordionModule,
    DxRadioGroupModule,
    DxContextMenuModule,
    DxLookupModule,
    DxButtonGroupModule,
    DxTooltipModule,
    DxSliderModule,
    DxGalleryModule,
    DxDrawerModule, 
    DxToolbarModule,
  ]
})
export class DevextremeModule { }
